# Generated by Django 2.1.1 on 2019-08-22 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_radiostation_scrapper'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scrapper',
            unique_together={('radio', 'python_path')},
        ),
    ]
