# Generated by Django 2.2.5 on 2019-09-20 14:21

from django.db import migrations, models
import django.db.models.deletion
import telegrambot.models


def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    RadioStation = apps.get_model("telegrambot", "RadioStation")
    Scrapper = apps.get_model("telegrambot", "Scrapper")

    db_alias = schema_editor.connection.alias
    for station in RadioStation.objects.using(db_alias).all():
        scrappers = Scrapper.objects.using(db_alias).filter(radio=station)
        if not scrappers:
            continue
        if scrappers.count() > 1:
            raise Exception("Radio station '{}' has more then one scrapper: {}.".format(station.name, scrappers))

        scrapper = scrappers[0]
        station.scrapper = scrapper.python_path
        station.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('telegrambot', '0003_auto_20190822_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiostation',
            name='scrapper',
            field=models.CharField(max_length=1000, null=True, validators=[telegrambot.models.validate_exists]),
        ),
        migrations.AlterField(
            model_name='scrapper',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrapper_model', to='telegrambot.RadioStation'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
