# Generated by Django 2.2.5 on 2019-09-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_playlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scrapper',
        ),
    ]
